#pragma once
/* Generated by tools/gen_wx_icons.py. Do not edit; regenerate. */
#include "lvgl.h"

extern const lv_img_dsc_t wxi_cloud_l;
#define WXI_CLOUD_L_X 95   /* offset inside the 384 px frame */
#define WXI_CLOUD_L_Y 73
extern const lv_img_dsc_t wxi_sun_l;
#define WXI_SUN_L_X 68   /* offset inside the 384 px frame */
#define WXI_SUN_L_Y 26
extern const lv_img_dsc_t wxi_moon_l;
#define WXI_MOON_L_X 107   /* offset inside the 384 px frame */
#define WXI_MOON_L_Y 67
extern const lv_img_dsc_t wxi_drops_l;
#define WXI_DROPS_L_X 108   /* offset inside the 384 px frame */
#define WXI_DROPS_L_Y 210
extern const lv_img_dsc_t wxi_snow_l;
#define WXI_SNOW_L_X 126   /* offset inside the 384 px frame */
#define WXI_SNOW_L_Y 212
extern const lv_img_dsc_t wxi_bolt_l;
#define WXI_BOLT_L_X 158   /* offset inside the 384 px frame */
#define WXI_BOLT_L_Y 185
extern const lv_img_dsc_t wxi_fogbank_l;
#define WXI_FOGBANK_L_X 70   /* offset inside the 384 px frame */
#define WXI_FOGBANK_L_Y 106
#define WXI_FRAME_L 384

extern const lv_img_dsc_t wxi_cloud_s;
#define WXI_CLOUD_S_X 2   /* offset inside the 36 px frame */
#define WXI_CLOUD_S_Y 5
extern const lv_img_dsc_t wxi_sun_s;
#define WXI_SUN_S_X 1   /* offset inside the 36 px frame */
#define WXI_SUN_S_Y 1
extern const lv_img_dsc_t wxi_moon_s;
#define WXI_MOON_S_X 4   /* offset inside the 36 px frame */
#define WXI_MOON_S_Y 4
extern const lv_img_dsc_t wxi_drops_s;
#define WXI_DROPS_S_X 7   /* offset inside the 36 px frame */
#define WXI_DROPS_S_Y 26
extern const lv_img_dsc_t wxi_snow_s;
#define WXI_SNOW_S_X 8   /* offset inside the 36 px frame */
#define WXI_SNOW_S_Y 27
extern const lv_img_dsc_t wxi_bolt_s;
#define WXI_BOLT_S_X 13   /* offset inside the 36 px frame */
#define WXI_BOLT_S_Y 23
extern const lv_img_dsc_t wxi_fog_s;
#define WXI_FOG_S_X 4   /* offset inside the 36 px frame */
#define WXI_FOG_S_Y 27
#define WXI_FRAME_S 36

extern const lv_img_dsc_t wxi_sun_m;
#define WXI_SUN_M_X 0   /* offset inside the 48 px frame */
#define WXI_SUN_M_Y 0
extern const lv_img_dsc_t wxi_moon_m;
#define WXI_MOON_M_X 6   /* offset inside the 48 px frame */
#define WXI_MOON_M_Y 7
#define WXI_FRAME_M 48
